### ISSUE TITLE
this will cause  “Maximum call stack size exceeded”

### ISSUE THREAD

**Issue by tangerren** [ebeaufay/threedtiles#27]
https://github.com/ebeaufay/threedtiles/blob/4058ff536c31d7b039482803ef9ba20a245a55c9/src/tileset/OGC3DTile.js#L89
![image](https://github.com/ebeaufay/threedtiles/assets/16789187/9520e821-63e4-486e-8e6d-4014a5b893af)

**Comment by ebeaufay** [comment]
Any more info?
Do you have a tileset that causes the issue you can share?
What's your build environment?

**Comment by tangerren** [comment]
with VUE3+vite。
use this demo's tileset  
![image](https://github.com/ebeaufay/threedtiles/assets/16789187/ab48bcff-c4e6-4ade-84a6-3cc25dd995f4)

**Comment by ebeaufay** [comment]
Hmmh but this tileset works fine with vanilla JS as well as with the vite+r3f demo.

Must be something to do with vue3 or the way you call the OGC3DTile.update function.

Perhaps in debug, you can check that update is called only once per frame.

Also, do you know why the stack reports calls to 

OGC3DTILE.r3.update instead of just OGC3DTILE.update? Are you wrapping the library with custom code or is the build doing that automatically..

**Comment by tangerren** [comment]
is there an completable、independent、source code demo？

**Comment by ebeaufay** [comment]
This is the vanilla Js demo project : https://drive.google.com/file/d/14lipb5eUqfad-n7EUgXuXul-drPdLifV/view?usp=sharing

And the demo  project with R3F :
https://drive.google.com/file/d/1C102qriCsnra9EUbb8WzO4jZStp-eEah/view?usp=sharing

That's the only 2 I have
